### ISSUE TITLE
Uninitialized constant Project::User (NameError)

### ISSUE THREAD

**Issue by phortx** [xdissent/redmine_git_server#4]
When starting redmine with that plugin.

> /home/benny/workspaces/yaana/redmine/app/models/project.rb:31:in class:Project: uninitialized constant Project::User (NameError)
>   from /home/benny/workspaces/yaana/redmine/app/models/project.rb:18:in <top (required)>
>   from /home/benny/workspaces/yaana/redmine/app/models/principal.rb:22:in class:Principal
>   from /home/benny/workspaces/yaana/redmine/app/models/principal.rb:18:in <top (required)>
>   from /home/benny/workspaces/yaana/redmine/app/models/user.rb:20:in <top (required)>
>   from /home/benny/workspaces/yaana/redmine/plugins/redmine_git_server/init.rb:35:in block in <top (required)>
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:429:in _run__3825883275219170208__prepare__3441769035506547666__callbacks
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in __run_callback
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in _run_prepare_callbacks
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in run_callbacks
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:74:in prepare!
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:48:in prepare!
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/application/finisher.rb:47:in block in module:Finisher
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/initializable.rb:30:in instance_exec
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/initializable.rb:30:in run
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/initializable.rb:55:in block in run_initializers
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/initializable.rb:54:in each
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/initializable.rb:54:in run_initializers
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/application.rb:136:in initialize!
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in method_missing
>   from /home/benny/workspaces/yaana/redmine/config/environment.rb:14:in <top (required)>
>   from /home/benny/workspaces/yaana/redmine/config.ru:3:in require
>   from /home/benny/workspaces/yaana/redmine/config.ru:3:in block in <main>
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/rack-1.4.5/lib/rack/builder.rb:51:in instance_eval
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/rack-1.4.5/lib/rack/builder.rb:51:in initialize
>   from /home/benny/workspaces/yaana/redmine/config.ru:in new
>   from /home/benny/workspaces/yaana/redmine/config.ru:in <main>
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/rack-1.4.5/lib/rack/builder.rb:40:in eval
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/rack-1.4.5/lib/rack/builder.rb:40:in parse_file
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/rack-1.4.5/lib/rack/server.rb:200:in app
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/commands/server.rb:46:in app
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/rack-1.4.5/lib/rack/server.rb:304:in wrapped_app
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/rack-1.4.5/lib/rack/server.rb:254:in start
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/commands/server.rb:70:in start
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/commands.rb:55:in block in <top (required)>
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/commands.rb:50:in tap
>   from /home/benny/.rvm/gems/ruby-1.9.3-p374/gems/railties-3.2.12/lib/rails/commands.rb:50:in <top (required)>
>   from script/rails:6:in require
>   from script/rails:6:in <main>

As a workaround, I commented out line 35 in init.rb, which allows me to boot redmine.

https://github.com/redmine/redmine.git on branch 2.2-stable

**Comment by xdissent** [comment]
Yeah, 2.2-stable has a circular dependency issue in the Project model. It _should_ be referencing Principal rather than User, and has been updated in master. Here's the offending line in 2.2-stable: https://github.com/redmine/redmine/blame/2.2-stable/app/models/project.rb#L31
and in master: https://github.com/redmine/redmine/blame/master/app/models/project.rb#L31

I'm not sure there's much we can do other than run master or modify core 2.2-stabe, because trying to fix it in a monkey patch is just going to trigger the bug no matter what (which is what's happening exactly).

**Comment by phortx** [comment]
Ok, thank you. Since it's not a issue of redmine_git_server itself and the question is answerd, the issue is closed.
